### ISSUE TITLE
on eu.loyisa.cn dc server

### ISSUE THREAD

**Issue by Ali00035** [Cypphi/verified-retards#2]
![image](https://user-images.githubusercontent.com/92791541/139580271-01625591-e023-4d18-8947-0008e7007671.png)

**Comment by Ali00035** [comment]
@Cypphi

**Comment by Cypphi** [comment]
will add when im home

**Comment by Ali00035** [comment]
> will add when im home

k

**Comment by Cypphi** [comment]
I kinda don't know what to do with this as it's not very understandable for anyone outside of the hacking community
